const tips = {
  Flood: {
    high: [
      "Move valuables and documents to upper shelves or higher floors immediately.",
      "Do not walk or drive through floodwater, even if it looks shallow.",
      "Turn off electricity at the breaker if water may enter your home.",
      "Prepare to evacuate to higher ground when barangay officials advise it.",
      "Monitor PAGASA and Manila MDRRMO advisories until water levels drop.",
      "Keep children and older adults away from open drainage and fast water.",
      "Store drinking water in clean covered containers before water service is interrupted.",
      "Use flashlights instead of candles if power goes out during flooding.",
      "Stay away from downed wires, damaged posts, and submerged electrical outlets.",
      "Re-enter flooded rooms only after officials say it is safe and utilities are checked.",
    ],
    moderate: [
      "Clear nearby drains and canals before heavier rain arrives.",
      "Place important papers, medicine, and devices in waterproof containers.",
      "Prepare sandbags or barriers for low doorways.",
      "Charge phones and power banks while electricity is stable.",
      "Review the route to your nearest evacuation center.",
      "Keep ready-to-eat food, a flashlight, radio, batteries, and first aid items accessible.",
      "Move appliances and extension cords above the expected flood level.",
      "Check barangay flood warnings and share updates with neighbors who may miss them.",
      "Avoid parking vehicles in streets that usually become impassable.",
    ],
    low: [
      "Keep drainage around your home clean and free of trash.",
      "Store emergency contacts and barangay hotlines on every phone.",
      "Keep a small waterproof pouch for documents and medicine ready.",
      "Check PAGASA rainfall updates during rainy days.",
      "Find out if your street has a history of flooding and note the usual safe exits.",
      "Do not throw garbage into esteros, rivers, or drainage channels.",
      "Keep children from playing near canals even during light rain.",
    ],
  },
  Fire: {
    high: [
      "Evacuate immediately and call BFP 117 once you are safe.",
      "Do not use elevators or return inside for belongings.",
      "Stay low under smoke and cover your nose with cloth if needed.",
      "Warn nearby households, especially older adults and children.",
      "Meet your family at a safe outdoor point away from the fire.",
      "Close doors behind you if you can do it quickly to slow smoke and flame spread.",
      "If clothes catch fire, stop, drop, and roll until the flames are out.",
      "Do not open a hot door; use another exit or signal for help from a window.",
      "Keep streets and alleys clear so fire trucks can reach the area.",
    ],
    moderate: [
      "Inspect overloaded outlets and unplug unused appliances.",
      "Keep a working fire extinguisher near the kitchen.",
      "Clear hallways and exits so evacuation is fast.",
      "Check LPG hoses, regulators, and stove knobs before sleeping.",
      "Keep LPG cylinders upright in a ventilated area and close the valve after use.",
      "Never check an LPG leak with a flame; use soapy water and ventilate the area.",
      "Keep matches, lighters, and candles away from children and curtains.",
      "Replace damaged extension cords, loose outlets, and hot plugs immediately.",
    ],
    low: [
      "Avoid octopus wiring and overloaded extension cords.",
      "Never leave candles, chargers, or cooking unattended.",
      "Teach every household member how to call BFP 117.",
      "Unplug appliances before leaving home or sleeping when they are not needed.",
      "Keep flammable liquids, paper, and cloth away from stoves and electrical panels.",
      "Test smoke alarms regularly and replace weak batteries.",
      "Plan two exits from every sleeping area.",
    ],
  },
  Landslide: {
    high: [
      "Move away from steep slopes, cracked ground, or leaning trees immediately.",
      "Evacuate before heavy rain intensifies if your area has prior slope movement.",
      "Report fresh cracks, rumbling sounds, or sudden muddy water to the barangay.",
      "Do not sleep in rooms facing unstable slopes during heavy rain.",
      "Bring your go bag and avoid riverbanks or drainage channels.",
      "Leave areas below a slope if rocks, soil, or debris begin falling.",
      "Do not cross an active slide path; move sideways away from the flow.",
      "Keep away from roads or bridges blocked by landslide debris.",
      "Wait for MDRRMO or engineering clearance before returning to affected homes.",
    ],
    moderate: [
      "Redirect rainwater away from slopes and foundations.",
      "Plant deep-rooted vegetation where safe and approved.",
      "Check retaining walls for cracks after heavy rainfall.",
      "Prepare an evacuation path that avoids slope edges.",
      "Watch for new cracks on the ground, floors, walls, or pavements.",
      "Listen for unusual sounds such as cracking trees, moving rocks, or rumbling soil.",
      "Report clogged slope drainage or seepage that turns muddy after rain.",
      "Keep heavy items and stored water away from weak slope edges.",
    ],
    low: [
      "Monitor nearby slopes after long or intense rain.",
      "Keep drainage channels clear so water does not weaken soil.",
      "Know the nearest stable high-ground route.",
      "Avoid digging into slopes or removing vegetation without proper approval.",
      "Check geohazard advisories when planning repairs near steep ground.",
      "Ask barangay officials where the local landslide-prone areas are.",
    ],
  },
  "Fault Line": {
    high: [
      "Practice Drop, Cover, and Hold On with every household member.",
      "Secure cabinets, shelves, appliances, and mirrors to walls.",
      "Keep shoes, flashlight, whistle, and go bag near your bed.",
      "After shaking, move to an open area away from damaged structures.",
      "Have older buildings checked by a licensed structural professional.",
      "During shaking, stay indoors until it stops if you are already inside.",
      "Stay away from windows, glass, hanging objects, and heavy furniture.",
      "If outdoors, move away from buildings, posts, trees, and power lines.",
      "Expect aftershocks and avoid entering cracked or leaning structures.",
    ],
    moderate: [
      "Identify sturdy cover points in every room.",
      "Keep exits clear from cabinets and heavy objects.",
      "Store water, food, medicine, and radio good for at least 72 hours.",
      "Join barangay or MDRRMO earthquake drills.",
      "Strap LPG tanks and know how to shut off gas, electricity, and water.",
      "Set a family meeting point outside your home and outside your barangay.",
      "Keep emergency numbers and an out-of-area contact saved on all phones.",
      "Check if your home sits near liquefaction-prone or reclaimed ground.",
    ],
    low: [
      "Review your family communication plan after an earthquake.",
      "Check emergency supplies every month.",
      "Know how to shut off gas, electricity, and water.",
      "Move heavy objects to lower shelves before an earthquake happens.",
      "Keep a flashlight and slippers beside each bed.",
      "Take part in scheduled city, school, workplace, or barangay drills.",
    ],
  },
  Typhoon: {
    high: [
      "Stay indoors away from windows and glass doors.",
      "Evacuate early if advised, especially in flood-prone or weak structures.",
      "Secure roof sheets, outdoor items, and loose materials before winds strengthen.",
      "Charge power banks and prepare battery lights before outages.",
      "Monitor PAGASA bulletins and barangay announcements.",
      "Stay in a strong building and do not go outside during the calm eye of the typhoon.",
      "Avoid coasts, riverbanks, bridges, and low-lying roads during strong rain and wind.",
      "Bring your emergency kit if MDRRMO or barangay officials order evacuation.",
      "Switch off electricity and gas before leaving if it is safe to do so.",
    ],
    moderate: [
      "Clean gutters and downspouts before heavy rain.",
      "Trim risky branches near your house with proper assistance.",
      "Move outdoor furniture and tools indoors.",
      "Prepare drinking water and ready-to-eat food.",
      "Check roof fasteners, windows, and doors before winds become strong.",
      "Keep a battery radio ready in case mobile data or power is lost.",
      "Avoid unnecessary travel once wind signals or flood warnings are raised.",
      "Prepare supplies for infants, older adults, persons with disabilities, and pets.",
    ],
    low: [
      "Keep phones charged during typhoon alerts.",
      "Store emergency numbers and evacuation center details.",
      "Check roof leaks and windows before rainy season.",
      "Follow PAGASA updates even when the weather still looks calm.",
      "Know which routes flood first on the way to work, school, or evacuation sites.",
      "Keep rain gear, medicine, and copies of IDs ready in one bag.",
    ],
  },
  "Drainage Issue": {
    high: [
      "Report blocked drainage or missing covers to the barangay immediately.",
      "Keep children away from open manholes and fast-moving runoff.",
      "Remove trash from safe, reachable drainage grates before rain.",
      "Document recurring pooling areas and submit a report in MitigatePlus.",
      "Avoid dumping waste into canals or waterways.",
      "Mark or avoid open drainage covers until barangay or utility crews secure them.",
      "Do not step into murky pooled water because open holes may be hidden.",
      "Warn nearby households if runoff starts entering homes or electrical areas.",
      "Call for official help if clearing the blockage requires entering a canal or road lane.",
    ],
    moderate: [
      "Join or request regular canal cleanup in your street.",
      "Separate household waste so plastic does not block drains.",
      "Improve water flow away from your doorway where possible.",
      "Check drainage covers after heavy rain.",
      "Clear only surface trash that can be reached safely without opening manholes.",
      "Report illegal dumping, construction debris, or clogged waterways to barangay officials.",
      "Take photos of flood depth and location to support maintenance requests.",
      "Keep household chemicals and waste away from drains during cleanup.",
    ],
    low: [
      "Keep nearby gutters and drain mouths clear.",
      "Report early signs of stagnant water.",
      "Remind neighbors not to dispose trash in waterways.",
      "Sweep leaves and plastic away from curb inlets before rain starts.",
      "Cover trash bins so waste does not spill into canals.",
      "Support community cleanup drives that reduce flood-causing blockages.",
    ],
  },
  "Structural Damage": {
    high: [
      "Leave the structure if you see major cracks, sagging, or loud structural sounds.",
      "Ask the City Engineering Office or a licensed engineer for inspection.",
      "Do not repair load-bearing columns or beams without professional guidance.",
      "Avoid using rooms under sagging ceilings or damaged beams.",
      "Take photos and report the hazard to barangay officials.",
      "Keep people away from leaning walls, damaged stairs, and falling debris zones.",
      "Shut off electricity or gas only if it can be done without entering a dangerous area.",
      "Do not re-enter after an earthquake, fire, or flood until officials clear the building.",
      "Use barriers or warning signs to keep neighbors away from unstable parts.",
    ],
    moderate: [
      "Mark cracks and monitor if they widen after rain or shaking.",
      "Fix leaks quickly to prevent weakening of materials.",
      "Keep heavy loads away from damaged floors or walls.",
      "Schedule a structural inspection before making renovations.",
      "Check doors and windows that suddenly jam because frames may have shifted.",
      "Look for exposed steel bars, spalling concrete, tilted posts, or sagging beams.",
      "Keep photos with dates so engineers can compare changes over time.",
      "Avoid drilling, cutting, or chipping damaged columns and beams.",
    ],
    low: [
      "Keep a maintenance log for cracks, leaks, and repairs.",
      "Inspect roof, columns, and walls after earthquakes or typhoons.",
      "Avoid unauthorized structural changes.",
      "Secure heavy furniture so it does not worsen damage during shaking.",
      "Check drainage and roof leaks that can weaken walls over time.",
      "Ask qualified professionals before adding floors, water tanks, or heavy equipment.",
    ],
  },
};

const sources = {
  Flood: "Sources: Manila City DRRM Department/MDRRMD, PAGASA flood safety guidance",
  Fire: "Sources: Manila City DRRM Department/MDRRMD, Bureau of Fire Protection fire safety guidance",
  Landslide: "Sources: Manila City DRRM Department/MDRRMD, MGB geohazard guidance",
  "Fault Line": "Sources: Manila City DRRM Department/MDRRMD, PHIVOLCS earthquake guidance",
  Typhoon: "Sources: PAGASA tropical cyclone and storm surge guidance",
  "Drainage Issue": "Sources: Manila City DRRM Department/MDRRMD, PAGASA flood mitigation guidance",
  "Structural Damage": "Sources: Manila City DRRM Department/MDRRMD, PHIVOLCS/building inspection guidance",
};

export const getMitigationTips = (type, severity = "moderate") => {
  const hazard = tips[type] || tips.Flood;
  return hazard[severity] || hazard.moderate || hazard.low;
};

export const getMitigationTipSource = (type) => sources[type] || sources.Flood;
